[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
monitor_port = /dev/cu.usbmodem101
upload_port = /dev/cu.usbmodem101
monitor_filters = esp32_exception_decoder

lib_deps =
  bblanchon/ArduinoJson @ ^6.21.5
  pierremolinaro/acan2517FD @ ^2.1.16
  handmade0octopus/ESP32-TWAI-CAN @ ^1.0.1
  adafruit/Adafruit NeoPixel @ ^1.12.5
  arduino-libraries/Arduino_BMI270_BMM150 @ ^1.2.3
  sparkfun/SparkFun MMC5983MA Magnetometer Arduino Library @ ^1.0.5
  adafruit/Adafruit SSD1306 @ ^2.5.9
  mikalhart/TinyGPSPlus @ ^1.0.3

build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
